source 'https://rubygems.org'

ruby '2.3.0'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'chronic'
gem 'erubis', '~> 2.7.0'
gem 'minitest', :require => 'minitest/autorun', :group => 'test'
gem 'octokit'
gem 'oj'
gem 'omniauth-github'
gem 'padrino', '~> 0.12.4'
gem 'pg'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'redcarpet'
gem 'sass'
gem 'shotgun', :group => 'development'
gem 'sinatra'
gem 'thin'
