source 'https://rubygems.org'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'erubis', '~> 2.7.0'
gem 'minitest', :require => 'minitest/autorun', :group => 'test'
gem 'oj'
gem 'padrino'
gem 'pg'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'sass'
gem 'shotgun', :group => 'development'
gem 'sinatra', :git => 'git@github.com:sinatra/sinatra.git'
gem 'thin'
