source 'https://rubygems.org'

ruby '2.3.0'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'chronic'
gem 'erubis', '~> 2.7.0'
gem 'minitest', :require => 'minitest/autorun', :group => 'test'
gem 'octokit'
gem 'oj'
gem 'omniauth-github', '>= 1.1.2'
gem 'padrino', '~> 0.12.9'
gem 'pg'
gem 'rack-test', '>= 0.6.3', :require => 'rack/test', :group => 'test'
gem 'rake'
gem 'redcarpet'
gem 'sass'
gem 'shotgun', '>= 0.9.1', :group => 'development'
gem 'sinatra', '>= 2.0.0'
gem 'thin', '>= 1.7.0'
